name: Model Training Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      training_params:
        description: 'Epochs'
        required: true
        default: '117'

jobs:
  download_data:
    runs-on: ubuntu-latest
    steps:
      - name: Download Data
        run: wget https://s442333.students.wmi.amu.edu.pl/weather.csv

  training:
    runs-on: ubuntu-latest
    needs: [download_data]
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          ls -la
          docker build -t dckrimg .
        working-directory: ./

      - name: Train Model
        run: |
          docker run dckrimg python3 ml.py ${{ github.event.inputs.training_params }}

      - name: Copy Model Artifact
        run: |
          docker cp $(docker ps -lq):/scripts/model.onnx .

      - name: Print pwd
        run: |
          ls -la

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-artifact
          path: model.onnx
 
  evaluation:
    runs-on: ubuntu-latest
    needs: training
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: model-artifact
          path: ./

      - name: Print
        run: |
          ls -la

      - name: Build Docker image
        run: docker build -t dckrimg .
        working-directory: ./

      - name: Print docker files
        run: docker run dckrimg ls -la
      
      - name: Copy Model Artifact
        run: docker cp ./model.onnx $(docker ps -lq):/scripts/

      - name: Print docker files after copy
        run: |
          docker run dckrimg pwd
          docker run dckrimg ls -la

      - name: Evaluate Model
        run: docker run dckrimg python3 ml_test.py

