name: Model Training Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      training_params:
        description: 'Training parameters'
        required: true
        default: '117'

jobs:
  download_data:
    runs-on: ubuntu-latest
    steps:
      - name: Download Data
        run: wget https://s442333.students.wmi.amu.edu.pl/weather.csv

  training:
    runs-on: ubuntu-latest
    needs: [download_data]
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          ls -la
          docker build -t dckrimg .
        working-directory: ./

      - name: Train Model
        run: docker run dckrimg python3 ml.py ${{ github.event.inputs.training_params }}

  archive:
    runs-on: ubuntu-latest
    needs: training
    steps:
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: model-artifact
          path: model.onxx
  

  evaluation:
    runs-on: ubuntu-latest
    needs: archive
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: model-artifact

      - name: Build Docker image
        run: docker build -t dckrimg .
        working-directory: ./

      - name: Evaluate Model
        run: docker run dckrimg python3 ml_test.py

